name: build

on:
  workflow_run:
    workflows: [ "release" ]
    types: [ completed ]
  push:
    branches:
      - 'master'
jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.18.2 ]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Installation
        run: npm ci

      - name: Build NgxRepository
        run: npm run build:ngx-repository
        env:
          CI: true

      - name: Build NgxHttpRepository
        run: npm run build:ngx-http-repository
        env:
          CI: true

      - name: Build NgxFirestoreRepository
        run: npm run build:ngx-firestore-repository
        env:
          CI: true

      - name: Linter
        run: npm run lint

      - name: Test
        run: npm run test:ci

      - name: Send coverage to Coverall
        uses: coverallsapp/github-action@v1.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./coverage/merged/lcov.info

      - name: "Publish @paddls/ngx-repository"
        uses: pascalgn/npm-publish-action@1.3.9
        with:
          tag_name: "v%s"
          tag_message: "v%s"
          commit_pattern: "^release: v(\\S+)"
          workspace: "./dist/ngx-repository"
          publish_args: "--access public"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN_PADDLS }}
      - name: "PrePublish @witty-services/ngx-repository"
        uses: jossef/action-set-json-field@v1
        with:
          file: "./dist/ngx-repository/package.json"
          field: name
          value: "@witty-services/ngx-repository"
      - name: "Publish @witty-services/ngx-repository"
        uses: pascalgn/npm-publish-action@1.3.9
        with:
          commit_pattern: "^release: v(\\S+)"
          workspace: "./dist/ngx-repository"
          publish_args: "--access public"
          create_tag: "false"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN_PADDLS }}

      - name: "Publish @paddls/ngx-http-repository"
        uses: pascalgn/npm-publish-action@1.3.9
        with:
          commit_pattern: "^release: v(\\S+)"
          workspace: "./dist/ngx-http-repository"
          publish_args: "--access public"
          create_tag: "false"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN_PADDLS }}
      - name: "PrePublish @witty-services/ngx-http-repository"
        uses: jossef/action-set-json-field@v1
        with:
          file: "./dist/ngx-http-repository/package.json"
          field: name
          value: "@witty-services/ngx-http-repository"
      - name: "Publish @witty-services/ngx-http-repository"
        uses: pascalgn/npm-publish-action@1.3.9
        with:
          commit_pattern: "^release: v(\\S+)"
          workspace: "./dist/ngx-http-repository"
          publish_args: "--access public"
          create_tag: "false"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN_PADDLS }}

      - name: "Publish @paddls/ngx-firestore-repository"
        uses: pascalgn/npm-publish-action@1.3.9
        with:
          commit_pattern: "^release: v(\\S+)"
          workspace: "./dist/ngx-firestore-repository"
          publish_args: "--access public"
          create_tag: "false"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN_PADDLS }}
      - name: "PrePublish @witty-services/ngx-firestore-repository"
        uses: jossef/action-set-json-field@v1
        with:
          file: "./dist/ngx-firestore-repository/package.json"
          field: name
          value: "@witty-services/ngx-firestore-repository"
      - name: "Publish @witty-services/ngx-firestore-repository"
        uses: pascalgn/npm-publish-action@1.3.9
        with:
          commit_pattern: "^release: v(\\S+)"
          workspace: "./dist/ngx-firestore-repository"
          publish_args: "--access public"
          create_tag: "false"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN_PADDLS }}
