# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build

on:
  push:
    branches:
      - '**'
jobs:
  build_and_test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.16.0]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Installation
      run: npm ci
    - name: Build NgxRepository
      run: npm run build:ngx-repository
      env:
        CI: true
    - name: Build NgxHttpRepository
      run: npm run build:ngx-http-repository
      env:
        CI: true
    - name: Build NgxFirebaseRepository
      run: npm run build:ngx-firebase-repository
      env:
        CI: true
    - name: Linter
      run: npm run lint
    - name: Test
      run: npm run test:ci
